/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `department`;
CREATE TABLE `department` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` char(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `code` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `parentIds` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  `sort` tinyint(4) DEFAULT '0' COMMENT '排序字段',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

INSERT INTO `department` (`id`, `name`, `code`, `parentIds`, `updateTime`, `createTime`, `sort`) VALUES
(1, '技术部', 'dp_code_technology', '[null]', '2022-09-29 11:34:08', '2022-09-29 09:52:39', 0);
INSERT INTO `department` (`id`, `name`, `code`, `parentIds`, `updateTime`, `createTime`, `sort`) VALUES
(3, '技术1部', 'dp_code_technology_1', '[1]', '2022-09-29 10:31:11', '2022-09-29 10:31:11', 0);
INSERT INTO `department` (`id`, `name`, `code`, `parentIds`, `updateTime`, `createTime`, `sort`) VALUES
(4, '技术2部', 'dp_code_technology_2', '[1]', '2022-09-29 10:32:09', '2022-09-29 10:32:09', 0);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;