/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE `dept` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `deptName` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `userId` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `userName` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `userEmail` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `parentId` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `createTime` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

INSERT INTO `dept` (`_id`, `deptName`, `userId`, `userName`, `userEmail`, `parentId`, `updateTime`, `createTime`) VALUES
(9, '技术部', NULL, NULL, NULL, '[null]', NULL, NULL);
INSERT INTO `dept` (`_id`, `deptName`, `userId`, `userName`, `userEmail`, `parentId`, `updateTime`, `createTime`) VALUES
(19, '前端部门', '3', 'zbxiang', '1144653975@qq.com', '[9]', '2022-08-22 21:01:58', '2022-08-22 21:01:58');


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;